/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fees_management_system.frames;

import java.awt.Color;

/**
 *
 * @author Rijwank
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        pnl_add_course = new javax.swing.JPanel();
        btn_editCourse = new javax.swing.JLabel();
        pnl_add_fees = new javax.swing.JPanel();
        btn_addFees = new javax.swing.JLabel();
        pnl_search = new javax.swing.JPanel();
        btn_search = new javax.swing.JLabel();
        pnl_view_records = new javax.swing.JPanel();
        btn_viewRecord = new javax.swing.JLabel();
        pnl_view_report = new javax.swing.JPanel();
        btn_viewReport = new javax.swing.JLabel();
        pnl_about = new javax.swing.JPanel();
        btn_about = new javax.swing.JLabel();
        pnl_view_course = new javax.swing.JPanel();
        btn_viewCourse = new javax.swing.JLabel();
        pnl_logout = new javax.swing.JPanel();
        btn_logout = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fees Management System - Home");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("St. Mohammad Trust");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 170, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("School Of Science");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 380, 50));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Sector 14, Queens Road, Vaishali Nagar, Jaipur 302022");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 370, 20));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Sir Ali Mohammad");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, 240, 20));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 140));

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_add_course.setBackground(new java.awt.Color(0, 102, 102));
        pnl_add_course.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        pnl_add_course.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_editCourse.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btn_editCourse.setForeground(new java.awt.Color(204, 255, 255));
        btn_editCourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/img/edit.png"))); // NOI18N
        btn_editCourse.setText("Edit Course");
        btn_editCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_editCourseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_editCourseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_editCourseMouseExited(evt);
            }
        });
        pnl_add_course.add(btn_editCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 230, 140));

        jPanel4.add(pnl_add_course, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 260, 160));

        pnl_add_fees.setBackground(new java.awt.Color(0, 102, 102));
        pnl_add_fees.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        pnl_add_fees.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_addFees.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btn_addFees.setForeground(new java.awt.Color(204, 255, 255));
        btn_addFees.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/img/plus.png"))); // NOI18N
        btn_addFees.setText("  Add Fees");
        btn_addFees.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_addFeesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_addFeesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_addFeesMouseExited(evt);
            }
        });
        pnl_add_fees.add(btn_addFees, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 220, 140));

        jPanel4.add(pnl_add_fees, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 260, 160));

        pnl_search.setBackground(new java.awt.Color(0, 102, 102));
        pnl_search.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        pnl_search.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_search.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btn_search.setForeground(new java.awt.Color(204, 255, 255));
        btn_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/img/search-document.png"))); // NOI18N
        btn_search.setText("   Search");
        btn_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_searchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_searchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_searchMouseExited(evt);
            }
        });
        pnl_search.add(btn_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 210, 140));

        jPanel4.add(pnl_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 260, 160));

        pnl_view_records.setBackground(new java.awt.Color(0, 102, 102));
        pnl_view_records.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        pnl_view_records.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_viewRecord.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btn_viewRecord.setForeground(new java.awt.Color(204, 255, 255));
        btn_viewRecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/img/text-book-opened-from-top-view.png"))); // NOI18N
        btn_viewRecord.setText("  View Records");
        btn_viewRecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_viewRecordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_viewRecordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_viewRecordMouseExited(evt);
            }
        });
        pnl_view_records.add(btn_viewRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 240, 140));

        jPanel4.add(pnl_view_records, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 40, 260, 160));

        pnl_view_report.setBackground(new java.awt.Color(0, 102, 102));
        pnl_view_report.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        pnl_view_report.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_viewReport.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btn_viewReport.setForeground(new java.awt.Color(204, 255, 255));
        btn_viewReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/img/view report.png"))); // NOI18N
        btn_viewReport.setText(" View Report ");
        btn_viewReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_viewReportMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_viewReportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_viewReportMouseExited(evt);
            }
        });
        pnl_view_report.add(btn_viewReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 240, 140));

        jPanel4.add(pnl_view_report, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 290, 260, 160));

        pnl_about.setBackground(new java.awt.Color(0, 102, 102));
        pnl_about.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        pnl_about.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_about.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btn_about.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/img/about.png"))); // NOI18N
        btn_about.setText("About Us");
        btn_about.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_aboutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_aboutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_aboutMouseExited(evt);
            }
        });
        pnl_about.add(btn_about, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 140, 70));

        jPanel4.add(pnl_about, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 470, 210, 80));

        pnl_view_course.setBackground(new java.awt.Color(0, 102, 102));
        pnl_view_course.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        pnl_view_course.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_viewCourse.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btn_viewCourse.setForeground(new java.awt.Color(255, 255, 255));
        btn_viewCourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/img/text-book-opened-from-top-view.png"))); // NOI18N
        btn_viewCourse.setText(" View Course");
        btn_viewCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_viewCourseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_viewCourseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_viewCourseMouseExited(evt);
            }
        });
        pnl_view_course.add(btn_viewCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 230, 140));

        jPanel4.add(pnl_view_course, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, 260, 160));

        pnl_logout.setBackground(new java.awt.Color(0, 102, 102));
        pnl_logout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        pnl_logout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_logout.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btn_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/img/logout.png"))); // NOI18N
        btn_logout.setText("Logout");
        btn_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_logoutMouseExited(evt);
            }
        });
        pnl_logout.add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 140, 60));

        jPanel4.add(pnl_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 470, 190, 80));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 1200, 580));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_editCourseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editCourseMouseEntered
        Color clr = new Color(0, 51, 51);
        pnl_add_course.setBackground(clr);
    }//GEN-LAST:event_btn_editCourseMouseEntered

    private void btn_editCourseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editCourseMouseExited
        Color clr = new Color(0, 102, 102);
        pnl_add_course.setBackground(clr);
    }//GEN-LAST:event_btn_editCourseMouseExited

    private void btn_addFeesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addFeesMouseEntered
        Color clr = new Color(0, 51, 51);
        pnl_add_fees.setBackground(clr);
    }//GEN-LAST:event_btn_addFeesMouseEntered

    private void btn_addFeesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addFeesMouseExited
        Color clr = new Color(0, 102, 102);
        pnl_add_fees.setBackground(clr);
    }//GEN-LAST:event_btn_addFeesMouseExited

    private void btn_searchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_searchMouseEntered
        Color clr = new Color(0, 51, 51);
        pnl_search.setBackground(clr);
    }//GEN-LAST:event_btn_searchMouseEntered

    private void btn_searchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_searchMouseExited
        Color clr = new Color(0, 102, 102);
        pnl_search.setBackground(clr);
    }//GEN-LAST:event_btn_searchMouseExited

    private void btn_viewRecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_viewRecordMouseEntered
        Color clr = new Color(0, 51, 51);
        pnl_view_records.setBackground(clr);
    }//GEN-LAST:event_btn_viewRecordMouseEntered

    private void btn_viewRecordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_viewRecordMouseExited
        Color clr = new Color(0, 102, 102);
        pnl_view_records.setBackground(clr);
    }//GEN-LAST:event_btn_viewRecordMouseExited

    private void btn_viewReportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_viewReportMouseEntered
        Color clr = new Color(0, 51, 51);
        pnl_view_report.setBackground(clr);
    }//GEN-LAST:event_btn_viewReportMouseEntered

    private void btn_viewReportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_viewReportMouseExited
        Color clr = new Color(0, 102, 102);
        pnl_view_report.setBackground(clr);
    }//GEN-LAST:event_btn_viewReportMouseExited

    private void btn_aboutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_aboutMouseEntered
        Color clr = new Color(0, 51, 51);
        pnl_about.setBackground(clr);
    }//GEN-LAST:event_btn_aboutMouseEntered

    private void btn_aboutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_aboutMouseExited
        Color clr = new Color(0, 102, 102);
        pnl_about.setBackground(clr);
    }//GEN-LAST:event_btn_aboutMouseExited

    private void btn_viewCourseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_viewCourseMouseEntered
        Color clr = new Color(0, 51, 51);
        pnl_view_course.setBackground(clr);
    }//GEN-LAST:event_btn_viewCourseMouseEntered

    private void btn_viewCourseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_viewCourseMouseExited
        Color clr = new Color(0, 102, 102);
        pnl_view_course.setBackground(clr);
    }//GEN-LAST:event_btn_viewCourseMouseExited

    private void btn_logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseEntered
        Color clr = new Color(0, 51, 51);
        pnl_logout.setBackground(clr);
    }//GEN-LAST:event_btn_logoutMouseEntered

    private void btn_logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseExited
        Color clr = new Color(0, 102, 102);
        pnl_logout.setBackground(clr);
    }//GEN-LAST:event_btn_logoutMouseExited

    private void btn_addFeesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addFeesMouseClicked
        AddFees fees = new AddFees();
        fees.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_addFeesMouseClicked

    private void btn_searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_searchMouseClicked
        SearchRecord searchRecord = new SearchRecord();
        searchRecord.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_searchMouseClicked

    private void btn_editCourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editCourseMouseClicked
        EditCourse course = new EditCourse();
        course.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_editCourseMouseClicked

    private void btn_viewRecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_viewRecordMouseClicked
        ViewRecords view = new ViewRecords();
        view.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_viewRecordMouseClicked

    private void btn_viewReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_viewReportMouseClicked
        ViewReport report = new ViewReport();
        report.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_viewReportMouseClicked

    private void btn_viewCourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_viewCourseMouseClicked
        EditCourse course = new EditCourse();
        course.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_viewCourseMouseClicked

    private void btn_aboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_aboutMouseClicked
        CopyrightPage copy = new CopyrightPage();
        copy.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_aboutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_about;
    private javax.swing.JLabel btn_addFees;
    private javax.swing.JLabel btn_editCourse;
    private javax.swing.JLabel btn_logout;
    private javax.swing.JLabel btn_search;
    private javax.swing.JLabel btn_viewCourse;
    private javax.swing.JLabel btn_viewRecord;
    private javax.swing.JLabel btn_viewReport;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel pnl_about;
    private javax.swing.JPanel pnl_add_course;
    private javax.swing.JPanel pnl_add_fees;
    private javax.swing.JPanel pnl_logout;
    private javax.swing.JPanel pnl_search;
    private javax.swing.JPanel pnl_view_course;
    private javax.swing.JPanel pnl_view_records;
    private javax.swing.JPanel pnl_view_report;
    // End of variables declaration//GEN-END:variables
}
